//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.06 at 10:45:13 PM WAT 
//


package xml.soap.station;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.station package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.station
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddStationRequest }
     * 
     */
    public AddStationRequest createAddStationRequest() {
        return new AddStationRequest();
    }

    /**
     * Create an instance of {@link GetStationDetailsRequest }
     * 
     */
    public GetStationDetailsRequest createGetStationDetailsRequest() {
        return new GetStationDetailsRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link AddStationRequest.Body }
     * 
     */
    public AddStationRequest.Body createAddStationRequestBody() {
        return new AddStationRequest.Body();
    }

    /**
     * Create an instance of {@link GetStationDetailsRequest.Body }
     * 
     */
    public GetStationDetailsRequest.Body createGetStationDetailsRequestBody() {
        return new GetStationDetailsRequest.Body();
    }

    /**
     * Create an instance of {@link GetStationDetailsResponse }
     * 
     */
    public GetStationDetailsResponse createGetStationDetailsResponse() {
        return new GetStationDetailsResponse();
    }

    /**
     * Create an instance of {@link DockType }
     * 
     */
    public DockType createDockType() {
        return new DockType();
    }

    /**
     * Create an instance of {@link AllStationRequest }
     * 
     */
    public AllStationRequest createAllStationRequest() {
        return new AllStationRequest();
    }

    /**
     * Create an instance of {@link AllStationResponse }
     * 
     */
    public AllStationResponse createAllStationResponse() {
        return new AllStationResponse();
    }

    /**
     * Create an instance of {@link StationResponseType }
     * 
     */
    public StationResponseType createStationResponseType() {
        return new StationResponseType();
    }

}
