//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 05:07:20 PM WAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.xml", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.soap;
