//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.07 at 07:52:43 PM WAT 
//


package xml.soap.user;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserIdRequest }
     * 
     */
    public UserIdRequest createUserIdRequest() {
        return new UserIdRequest();
    }

    /**
     * Create an instance of {@link CiclistaIdRequest }
     * 
     */
    public CiclistaIdRequest createCiclistaIdRequest() {
        return new CiclistaIdRequest();
    }

    /**
     * Create an instance of {@link GetSaldoRequest }
     * 
     */
    public GetSaldoRequest createGetSaldoRequest() {
        return new GetSaldoRequest();
    }

    /**
     * Create an instance of {@link TransferPointsRequest }
     * 
     */
    public TransferPointsRequest createTransferPointsRequest() {
        return new TransferPointsRequest();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link ValidateTokenRequest }
     * 
     */
    public ValidateTokenRequest createValidateTokenRequest() {
        return new ValidateTokenRequest();
    }

    /**
     * Create an instance of {@link ValidateTokenResponse }
     * 
     */
    public ValidateTokenResponse createValidateTokenResponse() {
        return new ValidateTokenResponse();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link AddUserRequest }
     * 
     */
    public AddUserRequest createAddUserRequest() {
        return new AddUserRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link UserIdRequest.Body }
     * 
     */
    public UserIdRequest.Body createUserIdRequestBody() {
        return new UserIdRequest.Body();
    }

    /**
     * Create an instance of {@link UserResponse }
     * 
     */
    public UserResponse createUserResponse() {
        return new UserResponse();
    }

    /**
     * Create an instance of {@link AllUsersRequest }
     * 
     */
    public AllUsersRequest createAllUsersRequest() {
        return new AllUsersRequest();
    }

    /**
     * Create an instance of {@link UserListResponse }
     * 
     */
    public UserListResponse createUserListResponse() {
        return new UserListResponse();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link CiclistaIdRequest.Body }
     * 
     */
    public CiclistaIdRequest.Body createCiclistaIdRequestBody() {
        return new CiclistaIdRequest.Body();
    }

    /**
     * Create an instance of {@link CiclistaResponse }
     * 
     */
    public CiclistaResponse createCiclistaResponse() {
        return new CiclistaResponse();
    }

    /**
     * Create an instance of {@link AllCiclistasRequest }
     * 
     */
    public AllCiclistasRequest createAllCiclistasRequest() {
        return new AllCiclistasRequest();
    }

    /**
     * Create an instance of {@link CiclistaListResponse }
     * 
     */
    public CiclistaListResponse createCiclistaListResponse() {
        return new CiclistaListResponse();
    }

    /**
     * Create an instance of {@link CiclistaType }
     * 
     */
    public CiclistaType createCiclistaType() {
        return new CiclistaType();
    }

    /**
     * Create an instance of {@link GetSaldoRequest.Body }
     * 
     */
    public GetSaldoRequest.Body createGetSaldoRequestBody() {
        return new GetSaldoRequest.Body();
    }

    /**
     * Create an instance of {@link GetSaldoResponse }
     * 
     */
    public GetSaldoResponse createGetSaldoResponse() {
        return new GetSaldoResponse();
    }

    /**
     * Create an instance of {@link TransferPointsRequest.Body }
     * 
     */
    public TransferPointsRequest.Body createTransferPointsRequestBody() {
        return new TransferPointsRequest.Body();
    }

    /**
     * Create an instance of {@link TransferPointsResponse }
     * 
     */
    public TransferPointsResponse createTransferPointsResponse() {
        return new TransferPointsResponse();
    }

}
